enum ActionValue {
    FORM_1,
    FORM_2,
    FORM_3,
    FORM_4,
    FORM_1_FILLED,
    FORM_2_FILLED,
    FORM_3_FILLED,
    FORM_4_FILLED,
    COLOR_GRAY,
    COLOR_PURPLE,
    COLOR_GREEN,
    TASTE_BUBBLE,
    TASTE_MINT,
    TASTE_STRAW,
    TASTE_WATERMELON,
    GLAZE_ON,
    GLAZE_OFF,
    PACK_1,
    PACK_2,
    PACK_3,
    PACK_4,
}

export default ActionValue;